/*
A regular style.
*/
@book-fonts:    "Source Sans Pro Regular",
                "Source Han Sans SC Regular",
                "Noto Sans Mono CJK SC Regular",
                "Noto Sans Adlam Regular",
                "Noto Sans Adlam Unjoined Regular",
                "Noto Sans Armenian Regular",
                "Noto Sans Bamum Regular",
                "Noto Sans Batak Regular",
                "Noto Sans Bengali UI Regular",
                "Noto Sans Buginese Regular",
                "Noto Sans Buhid Regular",
                "Noto Sans Canadian Aboriginal Regular",
                "Noto Sans Chakma Regular",
                "Noto Sans Cham Regular",
                "Noto Sans Cherokee Regular",
                "Noto Sans Coptic Regular",
                "Noto Sans Devanagari UI Regular",
                "Noto Sans Ethiopic Regular",
                "Noto Sans Georgian Regular",
                "Noto Sans Gujarati UI Regular",
                "Noto Sans Gurmukhi UI Regular",
                "Noto Sans Hanunoo Regular",
                "Noto Sans Hebrew Regular",
                "Noto Sans Javanese Regular",
                "Noto Sans Kannada UI Regular",
                "Noto Sans Kayah Li Regular",
                "Noto Sans Khmer UI Regular",
                "Noto Sans Lao UI Regular",
                "Noto Sans Lepcha Regular",
                "Noto Sans Limbu Regular",
                "Noto Sans Lisu Regular",
                "Noto Sans Malayalam UI Regular",
                "Noto Sans Mandaic Regular",
                "Noto Sans Mongolian Regular",
                "Noto Sans Myanmar UI Regular",
                "Noto Sans New Tai Lue Regular",
                "Noto Sans NKo Regular",
                "Noto Sans Ol Chiki Regular",
                "Noto Sans Oriya UI Regular",
                "Noto Sans Osage Regular",
                "Noto Sans Osmanya Regular",
                "Noto Sans Samaritan Regular",
                "Noto Sans Saurashtra Regular",
                "Noto Sans Shavian Regular",
                "Noto Sans Sinhala UI Regular", "Noto Sans Sinhala Regular",
                "Noto Sans Sundanese Regular",
                "Noto Sans Symbols Regular",
                "Noto Sans Symbols2 Regular",
                "Noto Sans Syriac Eastern Regular",
                "Noto Sans Tagalog Regular",
                "Noto Sans Tagbanwa Regular",
                "Noto Sans Tai Le Regular",
                "Noto Sans Tai Tham Regular",
                "Noto Sans Tai Viet Regular",
                "Noto Sans Tamil UI Regular",
                "Noto Sans Telugu UI Regular",
                "Noto Sans Thaana Regular",
                "Noto Sans Thai UI Regular",
                "Noto Sans Tifinagh Regular",
                "Noto Sans Vai Regular",
                "Noto Sans Yi Regular",

                "Noto Sans Arabic UI Regular", "Noto Naskh Arabic UI Regular",
                
                "Noto Sans Anatolian Hieroglyphs Regular",
                "Noto Sans Avestan Regular",
                "Noto Sans Bassa Vah Regular",
                "Noto Sans Bhaiksuki Regular",
                "Noto Sans Brahmi Regular",
                "Noto Sans Carian Regular",
                "Noto Sans Caucasian Albanian Regular",
                "Noto Sans Cuneiform Regular",
                "Noto Sans Cypriot Regular",
                "Noto Sans Deseret Regular",
                "Noto Sans Duployan Regular",
                "Noto Sans Egyptian Hieroglyphs Regular",
                "Noto Sans Elbasan Regular",
                "Noto Sans Elymaic Regular",
                "Noto Sans Glagolitic Regular",
                "Noto Sans Gothic Regular",
                "Noto Sans Gunjala Gondi Regular",
                "Noto Sans Hanifi Rohingya Regular",
                "Noto Sans Hatran Regular",
                "Noto Sans Imperial Aramaic Regular",
                "Noto Sans Indic Siyaq Numbers Regular",
                "Noto Sans Inscriptional Pahlavi Regular",
                "Noto Sans Inscriptional Parthian Regular",
                "Noto Sans Kaithi Regular",
                "Noto Sans Kharoshthi Regular",
                "Noto Sans Khudawadi Regular",
                "Noto Sans Linear A Regular",
                "Noto Sans Linear B Regular",
                "Noto Sans Lycian Regular",
                "Noto Sans Lydian Regular",
                "Noto Sans Mahajani Regular",
                "Noto Sans Manichaean Regular",
                "Noto Sans Marchen Regular",
                "Noto Sans Masaram Gondi Regular",
                "Noto Sans Mayan Numerals Regular",
                "Noto Sans Medefaidrin Regular",
                "Noto Sans Meetei Mayek Regular",
                "Noto Sans Mende Kikakui Regular",
                "Noto Sans Meroitic Regular",
                "Noto Sans Miao Regular",
                "Noto Sans Modi Regular",
                "Noto Sans Mro Regular",
                "Noto Sans Multani Regular",
                "Noto Sans Nabataean Regular",
                "Noto Sans Newa Regular",
                "Noto Sans Nushu Regular",
                "Noto Sans Ogham Regular",
                "Noto Sans Old Hungarian Regular",
                "Noto Sans Old North Arabian Regular",
                "Noto Sans Old Permic Regular",
                "Noto Sans Old Persian Regular",
                "Noto Sans Old Sogdian Regular",
                "Noto Sans Old South Arabian Regular",
                "Noto Sans Old Turkic Regular",
                "Noto Sans Pahawh Hmong Regular",
                "Noto Sans Palmyrene Regular",
                "Noto Sans Pau Cin Hau Regular",
                "Noto Sans PhagsPa Regular",
                "Noto Sans Phoenician Regular",
                "Noto Sans Psalter Pahlavi Regular",
                "Noto Sans Rejang Regular",
                "Noto Sans Runic Regular",
                "Noto Sans Sharada Regular",
                "Noto Sans Siddham Regular",
                "Noto Sans SignWriting Regular",
                "Noto Sans Sogdian Regular",
                "Noto Sans Sora Sompeng Regular",
                "Noto Sans Soyombo Regular",
                "Noto Sans Syloti Nagri Regular",
                "Noto Sans Takri Regular",
                "Noto Sans Tirhuta Regular",
                "Noto Sans Ugaritic Regular",
                "Noto Sans Wancho Regular",
                "Noto Sans Warang Citi Regular",
                "Noto Sans Zanabazar Square Regular",

                "Noto Serif Tibetan Regular", "Noto Sans Tibetan Regular";


/*
A bold style is available for almost all scripts. Bold text is heavier than
regular text and can be used for emphasis. Fallback is a regular style.
*/
@semi-bold-fonts:
                "Source Sans Pro SemiBold",
                @bold-fonts;

/*
A bold style is available for almost all scripts. Bold text is heavier than
regular text and can be used for emphasis. Fallback is a regular style.
*/
@bold-fonts:    
                "Source Sans Pro Bold",
                "Source Han Sans SC Bold", 
                "Noto Sans Bold",
                "Noto Sans Armenian Bold",
                "Noto Sans Bengali UI Bold",
                "Noto Sans Cham Bold",
                "Noto Sans Cherokee Bold",
                "Noto Sans Devanagari UI Bold",
                "Noto Sans Ethiopic Bold",
                "Noto Sans Georgian Bold",
                "Noto Sans Gujarati UI Bold",
                "Noto Sans Gurmukhi UI Bold",
                "Noto Sans Hebrew Bold",
                "Noto Sans Kannada UI Bold",
                "Noto Sans Khmer UI Bold",
                "Noto Sans Lao UI Bold",
                "Noto Sans Malayalam UI Bold",
                "Noto Sans Myanmar UI Bold",
                "Noto Sans Oriya UI Bold",
                "Noto Sans Sinhala UI Bold", "Noto Sans Sinhala Bold",
                "Noto Sans Symbols Bold",
                "Noto Sans Tamil UI Bold",
                "Noto Sans Telugu UI Bold",
                "Noto Sans Thaana Bold",
                "Noto Sans Thai UI Bold",

                "Noto Sans Arabic UI Bold", "Noto Naskh Arabic UI Bold",

                "Noto Serif Tibetan Bold", "Noto Sans Tibetan Bold",

                @book-fonts;

/*
Italics are only available for the base font, not the other scripts.
For a considerable number of labels this style will make no difference to the regular style.
*/

@oblique-fonts: "Source Sans Pro Light", "Source Han Serif SC Light", "Noto Serif CJK SC Light", @book-fonts;

@italics-fonts: "Source Sans Pro Italic", @oblique-fonts;
